-- ! MAY BE SUBJECT TO UPDATES

-- public.genders (ENUM type - ("Male", "Female", "Unknown")
create table public.users (
  id bigint generated by default as identity not null,
  github_id bigint null,
  username text null,
  name text null,
  type text null,
  has_pronouns boolean null,
  gender public.gender null,
  location text null,
  avatar_url text null,
  profile_url text null,
  company text null,
  following bigint null,
  followers bigint null,
  hireable boolean null,
  bio text null,
  public_repos bigint null,
  public_gists bigint null,
  email text null,
  twitter_username text null,
  private_sponsor_count bigint null,
  created_at timestamp with time zone not null default now(),
  last_scraped timestamp with time zone null,
  is_enriched boolean not null default false,
  constraint users_pkey primary key (id),
  constraint users_github_id_key unique (github_id),
  constraint users_username_key unique (username)
) TABLESPACE pg_default;


create table public.user_activity (
  id bigint generated by default as identity not null,
  user_id bigint null,
  commit_count bigint null,
  pr_count bigint null,
  issues_count bigint null,
  code_review_count bigint null,
  created_at timestamp with time zone null default now(),
  constraint user_activity_pkey primary key (id),
  constraint user_activity_user_id_key unique (user_id),
  constraint user_activity_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


create table public.platform (
  id bigint generated by default as identity not null,
  user_id bigint null,
  platform text null,
  constraint platform_pkey primary key (id),
  constraint platform_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


-- public.status (ENUM type - ("pending", "completed", "failed", "skipped")
create table public.queue (
  id bigint generated by default as identity not null,
  username text null,
  depth bigint null,
  created_at timestamp with time zone not null default now(),
  status public.status null default 'pending'::status,
  constraint queue_pkey primary key (id),
  constraint queue_username_key unique (username)
) TABLESPACE pg_default;


create table public.sponsorship (
  id bigint generated by default as identity not null,
  sponsor_id bigint null,
  sponsored_id bigint null,
  constraint sponsorship_pkey primary key (id),
  constraint unique_sponsor_sponsored unique (sponsor_id, sponsored_id),
  constraint sponsorship_sponsor_id_fkey foreign KEY (sponsor_id) references users (id) on update CASCADE on delete CASCADE,
  constraint sponsorship_sponsored_id_fkey foreign KEY (sponsored_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;